name: Sander
favicon: null
layout_spectrum: 0.95889
typography_spectrum: 0.25365
title: Sander Datema
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8b0b3'
    - '#957964'
    - '#4f342b'
    - '#5da0d7'
    - '#ca4830'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
