name: Sander
favicon: null
layout_spectrum: 0.95889
typography_spectrum: 0.25365
title: Sander Datema
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#253949'
    - '#c5c6c8'
    - '#8294a2'
    - '#506476'
    - '#d1936d'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
